version: "3"
services:
    ligier:
        image: "docker.km3net.de/jpp:v14.1.0"
        command: JLigier -d2
        ports:
            - ${MONITORING_LIGIER_PORT}:5553

    ligiermirror:
        build: ./ligiermirror
        env_file:
            - .env
        command: JLigierMirror -H ${DAQ_LIGIER_IP}:${DAQ_LIGIER_PORT} -X monitoring_ligier_1:5553 -t "${TAGS_TO_MIRROR}"
        depends_on:
            - "ligier"

    backend:
        build: ./backend
        env_file:
            - .env
        volumes:
            - ./logs:/logs
            - ./plots:/plots
            - ./data:/data
        depends_on:
            - "ligier"

    frontend:
        build: ./frontend
        env_file:
            - .env
        ports:
            - ${WEBSERVER_PORT}:5000
        volumes:
            - ./logs:/logs
            - ./plots:/plots
            - ./data:/data

    livelog:
        build: ./livelog
        ports:
            - ${LOGGING_PORT}:9001
        volumes:
            - ./logs:/logs

