version: "3"
services:
    ligier:
        image: "docker.km3net.de/jpp:v14.1.0"
        command: JLigier -d2
        ports:
            - ${MONITORING_LIGIER_PORT}:5553

    backend:
        build: ./backend
        env_file:
            - monitoring.env
        volumes:
            - ./logs:/logs
        command:
            - supervisord -c supervisord.conf
        tty: true

    livelog:
        build: ./livelog
        ports:
            - ${LOGGING_PORT}:9001
        volumes:
            - ./logs:/logs

