version: "3"
services:
    ligier:
        image: "docker.km3net.de/jpp:v14.1.0"
        command: JLigier -d2
        ports:
            - ${MONITORING_LIGIER_PORT}:5553

    backend:
        command: supervisord -c supervisord.conf
